<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipsAndResourcesSeeder extends Seeder
{
    public function run(): void
    {
        // Define the image file path
        $imagePath = 'imgs/image 14.png'; // Make sure the image exists in public/images folder

        // Insert data into the database with image path
        DB::table('tips_and_resources')->insert([
            'title' => 'Understanding Eco and Carbon Footprint: A Step Toward Sustainability',
            'content' => "What is an Eco Footprint?
                An ecological (eco) footprint measures the demand humans place on Earth's ecosystems. It calculates the amount of biologically productive land and water area required to produce the resources an individual or group consumes and to absorb the waste they generate. This metric encompasses various factors, such as energy use, food consumption, and waste production.
                For instance, a community’s eco footprint includes the farmland needed to grow its food, forests to absorb CO2 emissions, and water bodies to supply fresh water. By comparing the eco footprint to the planet’s capacity to regenerate these resources, we can assess whether our consumption patterns are sustainable.
                What is a Carbon Footprint?
                A carbon footprint focuses specifically on greenhouse gas emissions, particularly carbon dioxide (CO2) and methane (CH4), generated by human activities. It is usually expressed in metric tons of CO2 equivalent (CO2e). The carbon footprint encompasses activities such as driving cars, heating homes, and producing goods.
                For example, burning fossil fuels for electricity and transportation contributes significantly to an individual’s carbon footprint. Food choices also play a role—animal-based diets typically result in higher emissions compared to plant-based diets.
                The Impact of Our Footprints
                Understanding and reducing eco and carbon footprints is crucial for mitigating environmental challenges such as climate change, deforestation, and biodiversity loss. High footprints strain Earth’s resources and contribute to global warming, threatening ecosystems and human livelihoods.",
            'image' => $imagePath,  // Store the image path in the database
        ]);
    }
}
